# This docker-compose file can currently only be used to set up
# a local development environment, NOT a production server!
version: '2'
services:
  app:
    container_name: expiry_sync_app
    hostname: expiry_sync_app
    build:
      context: ./setup/app
      dockerfile: Dockerfile
      args:
        config_path: .
        user_id: ${USER_ID}
        group_id: ${GROUP_ID}
    volumes:
      - ./expiry_sync_client:/srv/project
      - ./.git:/srv/.git
      - ./expiry_sync_client:/srv/expiry_sync_client
      - ./expiry_sync_server:/srv/expiry_sync_server
      - ./setup/app:/srv/config
    networks:
      - expiry_sync-net
  db:
    image: mysql
    hostname: expiry_sync_db
    container_name: expiry_sync_db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./setup/db/mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - expiry_sync-net
  mail:
    image: mailhog/mailhog
    container_name: expiry_sync_mail
    hostname: expiry_sync_mail
    networks:
      - expiry_sync-net
  web:
    container_name: expiry_sync_web
    hostname: expiry_sync_web
    build:
      context: ./setup/web
      dockerfile: Dockerfile
      args:
        user_id: ${USER_ID}
        group_id: ${GROUP_ID}
        config_path: .
    volumes:
      - ./expiry_sync_server:/srv/project
      - ./setup/web:/srv/config
    depends_on:
      - db
      - mail
    links:
      - db:db-server
      - mail:mail-server
    ports:
      - 443:443
    expose:
      - "443"
    networks:
      - expiry_sync-net

networks:
  expiry_sync-net:
    driver: bridge
